{
 "title": "Pressure transmitter variables",
 "description": "Demo dashbord",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "PV",
   "type": "graph",
   "description": "Pierwsza zmienna procesowa",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "pressurekpa" }
   ],
   "targets": [
    { "expr": "device_pv_value", "legendFormat": "PV" }
   ]
  },
  {
   "title": "SV, TV, FV",
   "type": "graph",
   "description": "Druga, trzecia i czwarta zmienna procesowa",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "device_sv_value", "legendFormat": "SV" },
    { "expr": "device_tv_value", "legendFormat": "TV" },
    { "expr": "device_fv_value", "legendFormat": "FV" }
   ]
  },
  {
   "title": "Percent of range",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "device_percent_of_range_value", "legendFormat": "PoR" }
   ]
  },
  {
   "title": "Percent Of Range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "device_percent_of_range_value" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 10 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    { "expr": "device_current_value", "legendFormat": "Current" }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"hart-exporter\"}"
    }
   ]
  },
  {
   "title": "Alloc MBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"hart-exporter\"}/1024/1024"
    }
   ]
  }
 ]
}